import Head from 'next/head';
import Image from 'next/image';
import { Inter } from "next/font/google";
import styles from '../styles/Home.module.css';
import Meta from '../components/Meta/Meta';

import useUser from '../data/use-user';

import Link from 'next/link';

import Spinner from '../components/Layout/Spinner';
import { useEffect } from 'react';

import useSWR, { Fetcher } from 'swr';

// const inter = Inter({ subsets: ['latin'] });

import { useSession, signIn, signOut } from 'next-auth/react';

export default function Home() {
	const fetcher = async (input: RequestInfo, init: RequestInit, ...args: any[]) => {
		const res = await fetch(input, init);
		return res.json();
	};

	const { data, error, isLoading } = useSWR('/api/loginStatus', fetcher);

	const { data: session, status } = useSession();

	// , axios.get, {
	// 	refreshInterval: 1000,
	// 	revalidateOnFocus: false,
	// 	revalidateOnReconnect: false,
	// 	revalidateOnMount: true,
	// 	shouldRetryOnError: false,
	// 	// onErrorRetry: (error, key, config, revalidate, { retryCount }) => {
	// 	// Never retry on 404.
	// 	if (error.status === 404) return;

	// 	// Only retry up to 10 times.
	// 	if (retryCount >= 10) re turn;

	// 	// Retrying twice as long as the previous attempt.
	// 	setTimeout(() => revalidate({ retryCount: retryCount + 1 }), 1000);
	// },
	// });

	function greetUser() {
		const date = new Date();
		const hour = date.getHours();

		if (hour < 12) {
			return 'Good morning';
		} else if (hour < 18) {
			return 'Good afternoon';
		} else {
			return 'Good evening';
		}
	}

	if (status === 'loading') return <Spinner size='large' type='fullscreen' />;

	if (session) {
		return (
			<>
				<br />
				<br />
				<br />
				<br />
				<br />
				<br />
				<p>{data && data.message}</p>
				<br />
				<br />
				Signed in as {session?.user?.email} <br />
				<button onClick={() => signOut()}>Sign out</button>
			</>
		);
	}
	return (
		<>
			<br />
			<br />
			<br />
			<p>{data && data.message}</p>
			<br />
			<br />
			<br />
			<br />
			Not signed in <br />
			<button onClick={() => signIn()}>Sign in</button>
		</>
	);

	return (
		<>
			<Meta title={'test'} description={'test'} />
			<main className={styles.main}>
				{session && (
					<>
						<h1>
							{greetUser()}, {session?.user?.name}.
						</h1>
						<h4>What do you want to do?</h4>
						<ul>
							<li>
								<Link href='/events'>See upcoming events</Link>
							</li>
							<li>
								<Link href='/dashboard'>Go to dashboard</Link>
							</li>
							<li>
								<Link href='/profile'>See your profile</Link>
							</li>
						</ul>
					</>
				)}
			</main>
		</>
	);
}

Home.auth = false;

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
